
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/nb01_load_and_plot_audio.ipynb

import numpy as np
from librosa.core import load
import matplotlib.pyplot as plt
from IPython.display import Audio

def load_audio(path, sample_rate = 16000):
    y, sr = load(path, sample_rate)
    return y, sr

def plot_signal(y, sr, title ='sound signal', return_audio = True):
    plt.figure(figsize = (15,6))
    plt.title(title)
    plt.plot(np.arange(len(y))/sr, y)
    plt.xlim(left = 0)
    plt.ylim(min(y)-0.1,max(y)+0.1)
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.show()
    if return_audio:
        return Audio(y,rate=sr)