
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/nb03_time_domain_features.ipynb

from exp.nb_nb02 import *

def average(frame):
    return np.mean(frame)

def energy(frame):
    return np.mean(frame*frame)

def zcr(frame):
    frame = np.sign(frame)
    return int(np.sum(np.abs(frame[:-1]-frame[1:])/2))

def autocorrelation(frame, a ):
    if a ==0:
        return energy(frame)
    return np.mean(frame[:-a]*frame[a:])

def autocorrelation_coefs(frame, num = 13):
    return [autocorrelation(frame, i) for i in range(num+1)]